### ISSUE TITLE
Epic: Project Submissions

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1125]
### Description
Currently users can submit their solution to a project by editing the project file in the curriculum repo and making a pull request to add it.

This has a few drawbacks such as solutions not being formatted correctly as links which in turn is a big drain on maintainers time as they need to add solutions and make sure they are formatted correctly. It also limits us greatly with how submission links look or can be used on the site as they are just markdown content in the lesson files.

We want to automate the project submission process by having a form the user will be able to add their project solution to and will be stored on the TOP database.

This will greatly simplify the submissions process and open the door to many future features on the TOP website, such as certifications, gamification and possibly code reviews between students.

### Todo's
This isn't an exhaustive list and will likely change in duration of this project.

#### Lesson Page
- [x] [Display initial Version of Project Submissions List on the Lesson Page](https://github.com/TheOdinProject/theodinproject/issues/1126)
- [x] [Clicking the Add Solution Button Should Open a Form in a Modal](https://github.com/TheOdinProject/theodinproject/pull/1186).
- [x] [When the Project Submission is Submitted the Users solution will be Added to the top of the Submissions List](https://github.com/TheOdinProject/theodinproject/pull/1186) 
- [x] [Display A List of the 10 Most Recent Submissions (This will change to 10 most popular later)](https://github.com/TheOdinProject/theodinproject/pull/1190)
- [x] [Add a "Edit" Button to the Users Submission Which Will open an Edit Form Modal](https://github.com/TheOdinProject/theodinproject/pull/1203).
- [x] [Add Delete Button to Edit Form Modal](https://github.com/TheOdinProject/theodinproject/pull/1204)

#### All Projects Page
- [x] [Display a list of all Submissions for a Project on a Separate Page](https://github.com/TheOdinProject/theodinproject/pull/1336)
- [x] [Paginate The Results so Projects with a lot of Submissions Don't have Performance Issues](https://github.com/TheOdinProject/theodinproject/pull/1336)

#### Dashboard
- [x] [Display the users submissions on their dashboard](https://github.com/TheOdinProject/theodinproject/pull/1337)

#### Reporting a Project
- [x] [Implement Report Endpoint and Model](https://github.com/TheOdinProject/theodinproject/pull/1133)
- [x] [Display a Report Icon on Each Submission which Will Open a Report Form in a Modal When Clicked.](https://github.com/TheOdinProject/theodinproject/pull/1268)
- [x] [When a Report is Submitted it Hides the Reported Submission in The Submissions List.](https://github.com/TheOdinProject/theodinproject/pull/1268)
- [x] [When a Flag is Submitted it Notifies Moderators on Discord with a Link to the Report in Active Admin.](https://github.com/TheOdinProject/theodinproject/pull/1283)
- [x] [Implement Active Admin Page Flag Page Which will Display Details about the Report](https://github.com/TheOdinProject/theodinproject/pull/1306).
- [x] [Implement Flow for when a Flag is Genuine](https://github.com/TheOdinProject/theodinproject/pull/1325)
- [x] [Implement Flow when a Flag is Fake](https://github.com/TheOdinProject/theodinproject/pull/1328)

**Comment by KevinMulhern** [comment]
Hey @adachiu, heres the issue for keeping track of this project. Feel free to add the mock ups to the issue when you get a chance please 🤘

**Comment by I3uckwheat** [comment]
congrats on closing this!
