### ISSUE TITLE
Epic: Add test suite for React components

### ISSUE THREAD

**Issue by leosoaivan** [TheOdinProject/theodinproject#1487]
Our React components need a comprehensive test suite, starting with full unit testing. This work should be encapsulated in an epic, with individual tickets/issues per component.

Using `react-testing-library` and `jest` (mainly for coverage reporting), we should write tests first for each of the following basic component, located in `app/javascript/component/project-submissions/components`:

- [ ] - create-form.js
- [ ] - edit-form.js
- [ ] - flag-form.js
- [ ] - like.js
- [ ] - modal.js
- [ ] - submission-title.js
- [ ] - submission.js
- [ ] - visible.js

**More details to come**
