### ISSUE TITLE
Chore: Update app to Rails 7

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/theodinproject#3049]
Given we're now teaching Rails 7 it would be good to have parity with the app too. 

[Official upgrade guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html)

**Todo**

* [x] Chore: Update config files for Rails 7 -> https://github.com/TheOdinProject/theodinproject/pull/3608
* [x] #3797
* [ ] Chore: Prepare app for Devise / Turbo incompatibility issues - [reference for one solution to compatibility issues](https://betterprogramming.pub/devise-auth-setup-in-rails-7-44240aaed4be)
* [ ] Chore: Prepare app for switch to Hotwire
* [x] Fix: Any new deprecations caused by Rails 7 update
* [ ] Chore: Remove UJS / old JS dependencies
* [x] #3057
* [x] #3017
* [x] #2884 -> https://github.com/TheOdinProject/theodinproject/pull/3608

**Notes**

- Now https://github.com/TheOdinProject/theodinproject/pull/3608 is merged the app is running on Rails 7, but there is still some follow up work to do. 
- Devise incompatibility may no longer be an issue

**Comment by ChargrilledChook** [comment]
There's a somewhat vague instruction in the upgrade guide 

> "Change the versions for Rails JavaScript packages in package.json and run yarn install, if running on Webpacker."

But no obvious info on where to find relevant versions. It is probably worth removing UJS, though

**Comment by KevinMulhern** [comment]
Thanks for getting this started @ChargrilledChook 💪  

Should we break some chores out of this?
* Chore for fixing the oauth2 depreciation 
* Maybe another for getting Hotwire in the app with turbo turned off.
* Another for replacing any Rails ujs behaviour we use.
etc

**Comment by ChargrilledChook** [comment]
> Thanks for getting this started @ChargrilledChook muscle

My pleasure 

> Should we break some chores out of this?

Great idea, I'll spin up a few issues out of this and keep track of them in this one

**Comment by ChargrilledChook** [comment]
Updated OP now https://github.com/TheOdinProject/theodinproject/pull/3608 is merged with some follow up work to do

**Comment by ChargrilledChook** [comment]
Outside of enabling Turbo, the app is now completely on Rails 7. I've opened a new story for the Turbo changes #3806
