### ISSUE TITLE
Chore: Complete Hotwire / Turbo Upgrade

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/theodinproject#3806]
## Context

We now patially use Turbo, but it is disabled by default for almost all pages. In order to make use of more features and modernise the app with current Rails 7 defaults it would be good to enable it globally. At the same time, we should clean up older Rails JavaScript on the app (ie, UJS) if and where possible.

## Tasks

- [ ] Toggle Turbo to be on on all pages by default
- [ ] Manually disable on any forms or links where appropriate
- [ ] Remove UJS from the app, and replace any behaviour as required
- [ ] Style the Turbo loading bar to use the site's colour theme (optional but nice to have)

## Acceptance Criteria

- [ ] Turbo is on globally
- [ ] UJS is removed from the app
- [ ] Rails tests continue to pass
- [ ] JavaScript tests continue to pass
- [ ] There are no regressions in site functionality

**Comment by ChargrilledChook** [comment]
Largely resolved by #3806, but a few follow ups:

- UJS seems to be a dependency of our React integration and is otherwise not causing too many issues - better to explore removing it in separate issue / if we remove ReactRails
- Styling the bar would still be a minor but nice addition
- Will follow up a minor regression in the project submission page when navigating backwards
