### ISSUE TITLE
Centralise to a single CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#3901]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description**
While working on #3892 I realized there are two copies of CONTRIBUTING.md within the TOP org: the one in this repo, and the one in the `.github` repo. TOP seems to consider this one to be the authoritative one: it existed earlier, tends to get updated, and is linked on several places. The `.github` one meanwhile hasn't been touched since it was created and was pinned to a version in May 2022, meaning it was 4 commits behind. On the other hand, because that one is in the `.github` repo, it gets linked automatically by GitHub in every create PR/issue view, and is therefore liable to be seen. 

Given the habit of two same but seperate files to drift apart, we should ideally centralize to a single authoritative source of truth. Given the GitHub autolinking, that should probably be the one in the `.github` repo.

**2. Acceptance Criteria:**

```[tasklist]
### Tasks
- [x] Decide upon a location for the centralized file
- [x] Update all links in the TOP org to point to that one
- [ ] ~~Drop the now unnecessary one~~
```

**Comment by ChargrilledChook** [comment]
I'm happy to centralize / streamline these into a single document, and I agree the .github version makes more sense. 

Rather than dropping the one in this repo I would prefer to make it specific to contributing to the web app. It should also point to the main generic contributing guide. That doesn't have to happen as part of this issue necessarily. 

Probably a worthwhile opportunity to review the guides as a whole and see if they're still relevant

**Comment by Asartea** [comment]
> Rather than dropping the one in this repo I would prefer to make it specific to contributing to the web app. It should also point to the main generic contributing guide. That doesn't have to happen as part of this issue necessarily.

Fair point, and that is indeed probably a better issue of the file in this repo

> Probably a worthwhile opportunity to review the guides as a whole and see if they're still relevant

I took a quick skim through when working on #3892 and didn't spot anything _too_ bad, but agree its probably worthwhile to review it in depth at some point; might work better as a seperate issue however?

**Comment by Asartea** [comment]
I think the repoint all links part of this should be ready for work? I think it would be best to split update the file and rewrite the version in this repo to be repo-specific into two new issues

**Comment by ChargrilledChook** [comment]
Sounds good @Asartea, feel free to comment here or in the contributors channel if you need any extra input

**Comment by Asartea** [comment]
All links not in this repo have been repointed; I'm going to file another issue for what to do with those
