### ISSUE TITLE
Chore: Switch Submissions from React to Hotwire

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#3908]
Just an epic to keep me right as this chore progresses.

**2. Acceptance Criteria:**
```[tasklist]
### Tasks
- [x] Add project submissions v2 feature flag
- [x] Display submissions with Hotwire
- [x] Add submissions using Hotwire
- [x] https://github.com/TheOdinProject/theodinproject/pull/3907
- [ ] https://github.com/TheOdinProject/theodinproject/pull/3924
- [ ] https://github.com/TheOdinProject/theodinproject/pull/3929
- [ ] https://github.com/TheOdinProject/theodinproject/pull/3967
- [ ] https://github.com/TheOdinProject/theodinproject/pull/4007
```

**Comment by ChargrilledChook** [comment]
Great idea :tada: 

One nice feature with the new task list thing - if you add a plain link to a PR or issue eg `https://github.com/TheOdinProject/theodinproject/pull/3839` you get pretty nice formatting, as well as tracking assignee - should also do all the linking without needing to comment on the child issues. Example:

```[tasklist]
### React Migration Epic Example
- [x] https://github.com/TheOdinProject/theodinproject/pull/3839
- [x] https://github.com/TheOdinProject/theodinproject/pull/3852
- [x] https://github.com/TheOdinProject/theodinproject/pull/3907
- [ ] Flag submissions using Hotwire
- [ ] Vote on submissions using Hotwire
```

**Comment by KevinMulhern** [comment]
Nice! thanks for the tip @ChargrilledChook. Still getting used to these new task lists lol

**Comment by KevinMulhern** [comment]
Finished the main part of the work on this. Feature parity has been achieved with the React version of the project feature. 

Next step is a gradual rollout. Using Flipper we can... 
1. First roll it out to 25% of users to monitor how it performs and reduce impact of any problems.
2. Then to 50%
3. After that, enabling for everyone.

Once it's fully enabled, I'll start the clean up job with removing the old React version.

**Comment by ChargrilledChook** [comment]
Loved the phased approach you took here, especially with the feature flag :clap: 

Would love to see us use this "mini epic" approach more in the future!

**Comment by KevinMulhern** [comment]
Enabled for 25% of users

**Comment by KevinMulhern** [comment]
Sentry has been quiet and things seem to be stable - upping to 50%

**Comment by KevinMulhern** [comment]
No negative feedback and Sentry is still quiet - enabling for everybody. I'll leave this open for a day or two incase there are any problems and we need to switch back to the old version temporarily.
