### ISSUE TITLE
Extract rules to top-meta and fetch/parse them from there onto the app

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/theodinproject#4022]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

For building a new feature of for odin-bot, it'd help the developers if the community discord rules existed in a markdown file. We could duplicate the rules into a markdown file somewhere, but then there would be two sources of truth for that information. Keeping them in-sync would be a problem.

So a solution could be to extract the rules into a markdown file that lives in the [top-meta repo](https://github.com/TheOdinProject/top-meta). The Odin site can fetch and parse this in a similar fashion to how it currently works with the curriculum repo's lessons. This allows one source of truth for the rules to live on top-meta, and other tools (ie the site and the bot) can programmatically interact with that file.

**2. Acceptance Criteria:**
- [ ] Create a copy of the current rules on the top-meta repo
- [ ] Have the app read the new markdown file in top-meta rather than having the rules hardcoded in [this erb file](https://github.com/TheOdinProject/theodinproject/blob/main/app/views/guides/community/rules.html.erb)

**Comment by Asartea** [comment]
Isn't this covered by https://github.com/TheOdinProject/top-meta/issues/281 ?

**Comment by ManonLef** [comment]
@Asartea it's part of it. This change needs to happen for several reasons too :)

**Comment by ManonLef** [comment]
@JoshDevHub Just to be sure regarding the acceptance criteria: The copy will become the source of truth correct? And the other file will be manually updated or removed so we don't have 2 copies to maintain?  

The issue we've had in the past was one of the copies being forgotten and getting outdated so I just want to be extra extra sure :D

I will also assign this to you since this was already discussed on discord afaik.

**Comment by JoshDevHub** [comment]
PR to the top-meta repo with the rules in a Markdown file: https://github.com/TheOdinProject/top-meta/pull/288
