### ISSUE TITLE
Cleanup buttons on /about

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#4118]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
`/about` contains three buttons at the bottom: to Discord, to `/contributing`, and to donate. Two of these already have button helpers (`chat_button` and `contribute_button` respectively), and the third should probably be a button. The existing buttons are exact replicas of the button helpers, and should be replaced with them

**2. Acceptance Criteria:**

```[tasklist]
### Tasks
- [ ] The Discord button is replaced by `<%= chat_button %>
- [ ] The Contribute buttons is replaced by `<%= contribute_button %>
- [ ] A new `donate_button` is created, using the code from https://github.com/TheOdinProject/theodinproject/blob/c37133960a88ef0d43871752ee2e1bcc7f6c654e/app/views/shared/_footer.html.erb#L12-L15
- [ ] Tests are created for this button
- [ ] The Donate button is replaced by <%= donate_button %>
```

**Comment by Aadya2901** [comment]
Hi, I’d like to work on cleaning up the buttons on the About page.
I’m familiar with HTML and CSS and will test the changes locally before submitting a PR.
Could you please assign this issue to me if it’s available?

**Comment by Arnav-Agarwal-01** [comment]
I would like to work on this issue. Please assign this to me. Thankyou.

**Comment by CouchofTomato** [comment]
@KevinMulhern Is this still needed?

**Comment by mao-sz** [comment]
Thanks @Asartea, makes sense.
Is this something you'd still like to be assigned to?

**Comment by Arnav-Agarwal-01** [comment]
I would like to be assigned to it

**Comment by CouchofTomato** [comment]
@mao-sz I assume we've given enough time for OP to come forward?
