### ISSUE TITLE
Chore: Upgrade to Rails 7.1

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/theodinproject#4735]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Chore: brief description of chore` format, e.g. `Chore: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Chore description

Upgrade our Rails version to 7.1.x.x

### Acceptance criteria

- [ ] The app is running on Rails 7.1
- [ ] No regressions

### Additional Comments

This can potentially be split up into several PR's with a phased approach. 
- First, upgrading the version and ensuring tests still pass
- Working through the `config/initializers/new_framework_defaults_7_1.rb` file (this step could be multiple PRs in itself)
- Finally, changing the framework defaults in `config/application.rb` to 7.1

```[tasklist]
### Tasks
- [x] Upgrade Rails version
- [x] Upgrade Rails Javascript packages* (*We appear to already be ahead of the curve here)
- [ ] Enable settings in `new_framework_defaults_7_1` (see below)
- [ ] Configure framework default to 7.1
```

- First PR for toggling low risk config https://github.com/TheOdinProject/theodinproject/pull/4737

```[tasklist]
### Framework defaults tasks
- [ ] ⚠️⚠️⚠️ Active Record Encryption changes ⚠️⚠️⚠️
- [ ] Enable the Active Job `BigDecimal` argument serializer
- [ ] Specify the default serializer used by `MessageEncryptor` and `MessageVerifier` instances.
- [ ] ⚠️⚠️⚠️ Enable a performance optimization that serializes message data and metadata # together. ⚠️⚠️⚠️
- [ ] ⚠️⚠️⚠️ Enable a performance optimization that serializes Active Record models ⚠️⚠️⚠️
- [ ] ⚠️⚠️⚠️ Change the format of the cache entry. ⚠️⚠️⚠️
- [ ] Disable automatic column serialization into YAML.
- [x] Enable before_committed! callbacks on all enrolled records in a transaction.
- [x] No longer add autoloaded paths into `$LOAD_PATH`.
- [x] Remove the default X-Download-Options headers
- [x] Do not treat an `ActionController::Parameters` instance
- [x] No longer run after_commit callbacks on the first of multiple Active Record
- [x] Configures SQLite with a strict strings mode, which disables double-quoted string literals.
- [x] Disable deprecated singular associations names.
- [x] Specify if an `ArgumentError` should be raised for `Rails.cache`
- [x] Specify whether Query Logs will format tags using the SQLCommenter format
- [x] Set the maximum size for Rails log files.
- [x] Enable raising on assignment to attr_readonly attributes
- [x] Enable validating only parent-related columns for presence
- [x] Enable precompilation of `config.filter_parameters`
- [x] Run `after_commit` and `after_*_commit` callbacks in the order they are defined in a model.
- [x] Whether a `transaction` block is committed or rolled back when exited via `return`, `break` or `throw`.
- [x] Controls when to generate a value for <tt>has_secure_token</tt> declarations.
- [x] Configure Action View to use HTML5 standards-compliant sanitizers when they are supported on your platform.
- [x] Configure Action Text to use an HTML5 standards-compliant sanitizer when it is supported on your platform.
- [x] Configure the log level used by the DebugExceptions middleware when logging
- [x] Configure the test helpers in Action View, Action Dispatch, and rails-dom-testing to use HTML5 parsers.
```

**Comment by ChargrilledChook** [comment]
Related PR pointing to main one that toggles the lower risk config changes https://github.com/TheOdinProject/theodinproject/pull/4737
