### ISSUE TITLE
Redesign: Minimum left to do until we can ship

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#635]
This is a stake in the ground so we can keep track of whats the minimum left to do before we can ship the redesign 🎉 

### Overview
- [x] Refactor forms to use generic structure and styles, implement password pages, add validations to all forms
- [x] Get the curriculum path to a usable state
- [x] Complete any remaining clean up and mic tasks

---
### Forms
**Misc**
- [x] [Refactor the auth forms component to make it more generic, the styles and structure will then be able to be used on other forms on the site. Implement this on the sign up and sign in pages first.](https://github.com/TheOdinProject/theodinproject/issues/680)

**Login and Sign up Pages**
- [x] [form validations](https://github.com/TheOdinProject/theodinproject/issues/675)
- [x] google oauth needs to be set up in production

**Request Password Reset and New Password pages**
- [x] Implement new design on the  request password reset page
- [x] Implement new design on the new password page
- [x] Validations for both forms

**Settings page**
- [x] [Needs redone to make it work differently (removing best in place)](https://github.com/TheOdinProject/theodinproject/issues/622)
- [x] [Refactor form to use new generic form component styles](https://github.com/TheOdinProject/theodinproject/issues/666)
- [x] [Form validations]()
- [x] [Fix error with settings form not submitting correctly](https://github.com/TheOdinProject/theodinproject/issues/701)

---

### Curriculum path

**Curriculum page**
- [x] [Visual indication to show a course is in progress and how much progress a user has made on the course](https://github.com/TheOdinProject/theodinproject/issues/707)
- [x] Visual indication to show a course has been completed

**Course page**
- [x] [lesson complete visual indication](https://github.com/TheOdinProject/theodinproject/issues/669)
- [x] Differentiate project lessons visually

**Lesson page**
- [x] [Identify any problems with lesson content and fix them](https://github.com/TheOdinProject/theodinproject/issues/671)
- [x] Implement styles for multiline code blocks
- [x] [Implement new design for the bottom button component](https://github.com/TheOdinProject/theodinproject/issues/708)
- [x] [Implement completing a lesson and un-completing a lesson functionality with the bottom
buttons](https://github.com/TheOdinProject/theodinproject/issues/708)

---

### Clean up and Misc tasks

**Navbar**
- [x] [More mobile bug fixes from the last review](https://github.com/TheOdinProject/theodinproject/issues/634)
- [x] extracting out the the links from the user drop down and displaying them on the mobile nav - can be worked on after bug fixes to navbar

**Dashboard**
- [x] [Visual progress indicator for a course](https://github.com/TheOdinProject/theodinproject/issues/707)
- [x] Course completed visual indicator - change start button to completed

**About Page**
- [x] [Overview of Odin section initial implementation](https://github.com/TheOdinProject/theodinproject/issues/661)
- [x] [Fix mobile issues with the overview section](https://github.com/TheOdinProject/theodinproject/issues/677)
- [x] [Overview of Odin section content](https://github.com/TheOdinProject/theodinproject/issues/678)

**Lesson Page**
- [x] [Viking adverts](https://github.com/TheOdinProject/theodinproject/issues/757)

**404 page**
- [x] [Needs initial design implemented](https://github.com/TheOdinProject/theodinproject/issues/419)
