### ISSUE TITLE
Redirect for deleted Introduction to web development course

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#788]
We have been getting a lot of errors from outside links directing users to the deleted "Introduction to web development" course.

It would be good to redirect these users to the web dev 101 course instead.

**Task:**
* Set up a redirect to the Web development 101 course for any routes that match `/courses/introduction-to-web-development/`

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by JonathanYiv** [comment]
I would like to lay claim to this one

**Comment by KevinMulhern** [comment]
Its all yours @JonathanYiv, thank you 😄
